modLoader="lowcodefml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="icon.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="eclipticseasons"
mandatory=true
versionRange="[0.12.7,)"
ordering="AFTER"
side="BOTH"
